apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-bank-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure-bank-app
  template:
    metadata:
      labels:
        app: insecure-bank-app
    spec:
      containers:
      - name: insecure-bank
        image: insecure-bank
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
