apiVersion: v1
kind: Service
metadata:
  name: insecure-bank-service
spec:
  type: NodePort
  selector:
    app: insecure-bank-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
