name: Build and scan

# Controls when the action will run. 
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  aqua:
    name: Aqua Code Scan 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Aqua scanner
        uses: docker://aquasec/aqua-scanner
        with:
          args: trivy fs --debug --scanners config,vuln,secret --sast . 
          # To customize which severities to scan for, add the following flag: --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          # To enable SAST scanning, add: --sast
          # To enable npm/dotnet non-lock file scanning, add: --package-json / --dotnet-proj
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          GITHUB_TOKEN: ${{ github.token }}
          TRIVY_RUN_AS_PLUGIN: 'aqua'
          # use the below 2 lines only if environments are deployed in eu region
          # AQUA_URL: https://api.eu-1.supply-chain.cloud.aquasec.com
          # CSPM_URL: https://eu-1.api.cloudsploit.com

  